[package]
authors = ["Jerel Unruh <mail@unruhdesigns.com>"]
description = "Membrane is an opinionated crate that generates a Dart package from a Rust library. Extremely fast performance with strict typing and zero copy returns over the FFI boundary via bincode."
edition = "2018"
keywords = ["dart", "ffi", "flutter", "bindings", "codegen"]
license = "Apache-2.0"
name = "membrane"
readme = "../README.md"
repository = "https://github.com/jerel/membrane"
version = "0.6.2"

[lib]
crate-type = ["lib"]
doctest = false

[features]
generate = ["membrane_macro/generate"]
skip-generate = ["membrane_macro/skip-generate"]

[dependencies]
allo-isolate = "0.1.11"
bincode = {version = "1.3"}
ffi_helpers = "0.2"
futures = "0.3"
heck = "0.3"
inventory = "0.1"
membrane_macro = {version = "^0.5", path = "../membrane_macro"}
membrane_types = {version = "^0.3", path = "../membrane_types"}
regex = "1.5"
serde = {version = "1.0", features = ["derive"]}
serde-generate = "0.20.4"
serde-reflection = "0.3.5"

[dev-dependencies]
example = {path = "../example"}
pretty_assertions = "1.0.0"
serial_test = "0.5.1"
trybuild = "1.0"
