name: Tests

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1

    - name: Update apt
      run: sudo apt-get update

    - name: Install libclang
      run: sudo apt-get install -y libclang-dev

    - name: Rust tests
      run: cargo test --verbose --features c-example

    - name: Rust build workspace
      run: cargo build --verbose

    - name: Rust build example
      working-directory: ./example
      run: cargo build --verbose

    - name: Rust generate Dart example
      working-directory: ./example
      run: cargo run

    - name: Dart run example
      working-directory: ./dart_example
      run: |
        dart compile exe -D --enable-asserts bin/dart_example.dart
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$(pwd)/../example/target/debug/"
        ./bin/dart_example.exe
